drawablepage.h: Add missing include
| In file included from ../git/src-qt5/Renderer-poppler.cpp:2:
| ../git/src-qt5/drawablepage.h:34:8: error: 'unique_ptr' in namespace 'std' does not name a template type
|    std::unique_ptr<Poppler::Page> page;
|         ^~~~~~~~~~
| ../git/src-qt5/drawablepage.h:34:3: note: 'std::unique_ptr' is defined in header '<memory>'; did you forget to '#include <memory>'?
| ../git/src-qt5/drawablepage.h:7:1:
| +#include <memory>

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>